### PR TITLE
Feature/sc linedensity interpolation

### PR DESCRIPTION
**Pull request by aoeftiger**
Adding a new space charge class with bunch profile interpolation (e.g. for double harmonics and anything else).

Up for discussion :smile: 

On another note, this patch introduces the new naming and refactoring of space charge classes discussed with @hannes-bartosik and @martinschwinzerl (cf. email 6.5.2020):

- `SpaceChargeCoasting` attributes are adapted to `SpaceChargeBunched` with `line_density` replaced by `number_of_particles` and an additional `circumference` attribute; the `track` method has been adjusted correspondingly
- `SpaceChargeBunched` becomes `SpaceChargeQGaussianProfile` and sports two new attributes (q and b factor for q-Gaussian which by default are 1.0 for the standard Gaussian) --> this class has yet to be extended to support q,b != 1

due to the renaming, the automated tests will have to be adapted, otherwise they throw:
```
==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_track.py _____________________
tests/test_track.py:23: in <module>
    pysixtrack.elements.SpaceChargeBunched,
E   AttributeError: module 'pysixtrack.elements' has no attribute 'SpaceChargeBunched'
=========================== short test summary info ============================
ERROR tests/test_track.py - AttributeError: module 'pysixtrack.elements' has ...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
```

### CODE REVIEW

**Comment by aoeftiger** [comment]
Here's a test for the new interpolating class:

[test.zip](https://github.com/SixTrack/pysixtrack/files/4770289/test.zip)

image

[Testing_SC_interpolated.pdf](https://github.com/SixTrack/pysixtrack/files/4770292/Testing_SC_interpolated.pdf)

**Comment by aoeftiger** [comment]
Just as a remark, I've added `np.interp` and `np.linspace` to `pysixtrack.mathlibs.MathlibDefault` for the moment -- suggestions for improvement are of course welcome.

It'd probably be nicer (for compute time) to avoid recomputing the bins for the interpolation at each track call, but I avoided touching the instantiation part (for precomputing and storing at `__init__`).

**Comment by aoeftiger** [comment]
The latest commit should solve any test errors and also bring the examples in line.

Now that `SpaceChargeCoasting` and `SpaceChargeQGaussianProfile` (former `SpaceChargeBunched`) have more or less the same argument signature, I'd even opt for removing the double set-up with all functions in bttools existing for both classes (such as `setup_spacecharge_bunched_in_line` and `setup_spacecharge_coasting_in_line`)...

**Comment by aoeftiger** [comment]
Updated with https://github.com/aoeftiger/pysixtrack/pull/2 .

Still needs to be adapted to the final layout and naming conventions (along with the still missing implementation of the q-Gaussian algorithm as in STL by @martinschwinzerl ) following the SixTrackLib counterpart https://github.com/SixTrack/sixtracklib/pull/132  .

**Review by martinschwinzerl — APPROVED** [review]
Reviewed and approved

**Pull request merged**
